// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  contact_section: dynamic(() => import("./ContactSection")),
  cta_footer: dynamic(() => import("./CtaFooter")),
  header_section: dynamic(() => import("./HeaderSection")),
  hero: dynamic(() => import("./Hero")),
  project_section: dynamic(() => import("./ProjectSection")),
  service_section: dynamic(() => import("./ServiceSection")),
  stack_section: dynamic(() => import("./StackSection")),
  testimonials: dynamic(() => import("./Testimonials")),
};
